import type { CoinChartBootstrapProps } from '../interface/CoinChart.interface';
import { useCoinChartBootstrapChart } from './CoinChartBootstrapChart.logic';
import { useCoinChartBootstrapSync } from './CoinChartBootstrapSync.logic';

export function useCoinChartBootstrap({
  candles,
  containerRef,
  priceScaleOverlayRef,
  isLoadingMore,
  hasMoreOlderCandles,
  onLoadOlderCandles,
  chartRef,
  seriesRef,
  ma10SeriesRef,
  ma50SeriesRef,
  ma100SeriesRef,
    ma200SeriesRef,
    pivotHighSeriesRef,
    pivotLowSeriesRef,
    structureMarkersRef,
    setHoveredCandle,
  setIsChartReady,
  candlesRef,
  onLoadOlderCandlesRef,
  hasMoreOlderCandlesRef,
  isLoadingMoreRef,
  requestedBeforeOpenTimeRef,
  pendingRangeRef,
  isProgrammaticRangeChangeRef,
  priceScaleZoomRef,
  priceScaleWheelDeltaRef,
  applyPriceScaleRangeRef,
  shouldFollowLatestRef,
}: CoinChartBootstrapProps) {
  useCoinChartBootstrapSync({
    candles,
    candlesRef,
    hasMoreOlderCandles,
    hasMoreOlderCandlesRef,
    isLoadingMore,
    isLoadingMoreRef,
    onLoadOlderCandles,
    onLoadOlderCandlesRef,
    applyPriceScaleRangeRef,
    priceScaleOverlayRef,
    priceScaleWheelDeltaRef,
    priceScaleZoomRef,
    seriesRef,
  });

  useCoinChartBootstrapChart({
    candlesRef,
    chartRef,
    containerRef,
    hasMoreOlderCandlesRef,
    isLoadingMoreRef,
    isProgrammaticRangeChangeRef,
    ma100SeriesRef,
    ma10SeriesRef,
    ma200SeriesRef,
    ma50SeriesRef,
    onLoadOlderCandlesRef,
    pendingRangeRef,
    pivotHighSeriesRef,
    pivotLowSeriesRef,
    requestedBeforeOpenTimeRef,
    seriesRef,
    setHoveredCandle,
    setIsChartReady,
    shouldFollowLatestRef,
    structureMarkersRef,
  });
}
